### ISSUE TITLE
definiton of dy_dark_channel

### ISSUE THREAD

**Issue by xiqi98** [legendongary/Proximal-Dehaze-Net-Complete#3]
Hi! I was trying to run your code, but I cannot find the method named "dy_dark_channel". Could you help me? Thanks!

**Comment by legendongary** [comment]
The source code is located in ./dehaze/source/dy_dark_channel.cu. To use this file, you have to compile it first using "mexcuda dy_dark_channel.cu".

**Comment by xiqi98** [comment]
Thank you very much!
