### ISSUE TITLE
Maximum variable size allowed on the device is exceeded

### ISSUE THREAD

**Issue by syzlhh** [legendongary/Proximal-Dehaze-Net-Complete#4]
Hi, we encounter a question while we run the test code in Windows 10 64, CUDA-9.0,1080TI. The error information is :
'Maximum variable size allowed on the device is exceeded'  when run the dy_dark_channel'.
Can you give me some help?

**Comment by legendongary** [comment]
From the error information, I guess the input image is too large for your machine. Perhaps you could first try a smaller one. The max image size tested on my 12 GB device is 1024x1024.

**Comment by syzlhh** [comment]
Thank you very much.  I update the matlab from 2015 to 2018, the problem is resolved.
